export default {
  banner: [
    {
      _id: '1',
      name: 'Control de Actividades en Excel',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur, rerum.',
      category: 'Marketing',
      image: './images/dashboard-1.png',
      imageHover: './images/dashboard-5.png',
      price: 10,
      discountPrice: 20,
      rating: 4.5,
      numReviews: 20,
      countInStock: 10,
    },
    {
      _id: '2',
      name: 'Control de Stock en Excel',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur, rerum.',
      category: 'Dashboards',
      image: './images/dashboard-2.png',
      imageHover: './images/dashboard-5.png',
      price: 10,
      discountPrice: 20,
      rating: 5,
      numReviews: 15,
      countInStock: 0,
    },
    {
      _id: '3',
      name: 'Control de Ventas en Excel',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur, rerum.',
      category: 'Ventas',
      image: './images/dashboard-3.png',
      imageHover: './images/dashboard-5.png',
      price: 10,
      discountPrice: 20,
      rating: 3,
      numReviews: 40,
      countInStock: 3,
    },
  ],
  products: [
    {
      _id: '1',
      name: 'Control de Actividades en Excel',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur, rerum.',
      category: 'Marketing',
      image: './images/dashboard-1.png',
      imageHover: './images/dashboard-5.png',
      price: 10,
      discountPrice: 20,
      rating: 4.5,
      numReviews: 60,
      countInStock: 10,
    },
    {
      _id: '2',
      name: 'Control de Stock en Excel',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur, rerum.',
      category: 'Dashboards',
      image: './images/dashboard-2.png',
      imageHover: './images/dashboard-5.png',
      price: 10,
      discountPrice: 20,
      rating: 5,
      numReviews: 20,
      countInStock: 0,
    },
    {
      _id: '3',
      name: 'Control de Ventas en Excel',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur, rerum.',
      category: 'Ventas',
      image: './images/dashboard-3.png',
      imageHover: './images/dashboard-5.png',
      price: 10,
      discountPrice: 20,
      rating: 3,
      numReviews: 18,
      countInStock: 3,
    },
    {
      _id: '4',
      name: 'Control Financiero Plantilla en Excel',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur, rerum.',
      category: 'Finanzas',
      image: './images/dashboard-1.png',
      imageHover: './images/dashboard-5.png',
      price: 10,
      discountPrice: 20,
      rating: 4.5,
      numReviews: 5,
      countInStock: 10,
    },
    {
      _id: '5',
      name: 'Indicadores de Ventas en Excel',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur, rerum.',
      category: 'Dashboards',
      image: './images/dashboard-2.png',
      imageHover: './images/dashboard-5.png',
      price: 10,
      discountPrice: 20,
      rating: 5,
      numReviews: 12,
      countInStock: 10,
    },
    {
      _id: '6',
      name: 'Plan Estratégico en Excel',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur, rerum.',
      category: 'Marketing',
      image: './images/dashboard-3.png',
      imageHover: './images/dashboard-5.png',
      price: 10,
      discountPrice: 20,
      rating: 4.5,
      numReviews: 20,
      countInStock: 10,
    },
  ],
};
